{
 "title": "Linky",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "UPS Charge",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "query": "select * from UPSL" }
   ]
  },
  {
   "title": "Puissance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    { "query": "SELECT * FROM PAPP" }
   ]
  },
  {
   "title": "Intensité",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "query": "select * from IINST" }
   ]
  },
  {
   "title": "UPS Autonomie",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "query": "SELECT value from UPSA" }
   ]
  },
  {
   "title": "KWh",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT (sum(\"value\") / 3600)  AS \"kWh\" FROM \"PAPP\" WHERE time >= now() - 24h GROUP BY time(1h)\n"
    }
   ]
  },
  {
   "title": "Internet",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "targets": [
    { "query": "SELECT * FROM CONN" }
   ]
  },
  {
   "title": "Puissance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    { "query": "SELECT * FROM PAPP" }
   ]
  },
  {
   "title": "Cout",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT (sum(\"value\") / 3600) * 0.2026 AS \"kWh\" FROM \"PAPP\" WHERE time >= now() - 24h GROUP BY time(1h)\n"
    }
   ]
  },
  {
   "title": "Pi Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "query": "SELECT * FROM TEMP" }
   ]
  }
 ]
}